cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "go-task/tap/go-task"
brew "go-task"
brew "packer"
brew "warrensbox/tap/tgswitch"
brew "warrensbox/tap/tfswitch"
brew "terraform"
brew "awscli"
brew "ngrok"
brew "yq"
brew "jq"
brew "ansible"
brew "pyenv"
brew "pipenv"