version: '3'

vars:
  DOCKER_ROOT_PATH: ../
  USER_PATH: /root

tasks:
  install:
    desc: installs docker
    cmds:
      - brew install docker
      - brew install docker-compose

  build:
    desc: builds the docker container
    cmds:
      - docker build -t dmake-shell -f dmake.dockerfile --platform=linux/amd64 .

  start:
    desc: starts the docker container
    cmds:
      - task: build
      - "cd {{.DOCKER_ROOT_PATH}} && docker run -it --rm -v $(pwd):{{.USER_PATH}} -v ~/.ssh:{{.USER_PATH}}/.ssh:ro -v ~/.aws:{{.USER_PATH}}/.aws:ro dmake-shell bash"